### ISSUE TITLE
are you interested in freelancing, i have a task dealing with via vgg image annotator

### ISSUE THREAD

**Issue by seekingdeep** [fredowski/homebrew-pspp#1]
@fredowski 
hi there, i have a freelance task if you are interested, dealing with "via_image_annotator.html", i want to include a new feature called "Combine Mode", basically, what i want is to be able to draw a line, and whatever regions my drawn line touches gets combined together into.

waiting for your reply

**Comment by fredowski** [comment]
Hi, thanks for asking but I have no time.

Cheers
