### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by irajankumar** [fredowski/homebrew-pspp#8]
Getting this error while installing on M1 Air book.

```
Undefined symbols for architecture arm64:
  "_rl_catch_signals", referenced from:
      _terminal_reader_create in libui.a[4](libui_la-terminal-reader.o)
  "_rl_echo_signal_char", referenced from:
      _handler in libui.a[4](libui_la-terminal-reader.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/ui/terminal/pspp] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by fredowski** [comment]
Thanks for hint. I restarted the build pipeline to see if this occurs also here on the github builder.

**Comment by fredowski** [comment]
The build works on the github runner. See:

https://github.com/fredowski/homebrew-pspp/actions/runs/11805214891

That is on MacOS 14.7 on arm64. Can you make sure that your brew system is up to date?

**Comment by irajankumar** [comment]
I just updated brew and re-tried and still getting same error.. I'm on Mac OS 15.1 and having M1 Chip.

Here's the full error:

```
Undefined symbols for architecture arm64:
  "_rl_catch_signals", referenced from:
      _terminal_reader_create in libui.a[4](libui_la-terminal-reader.o)
  "_rl_echo_signal_char", referenced from:
      _handler in libui.a[4](libui_la-terminal-reader.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/ui/terminal/pspp] Error 1
make[2]: *** Waiting for unfinished jobs....
libtool: link: clang -I/opt/homebrew/Cellar/gtk+3/3.24.43/include/gtk-3.0 -I/opt/homebrew/Cellar/pango/1.54.0/include/pango-1.0 -I/opt/homebrew/Cellar/harfbuzz/10.1.0/include/harfbuzz -I/opt/homebrew/Cellar/graphite2/1.3.14/include -I/opt/homebrew/Cellar/cairo/1.18.2/include -I/opt/homebrew/Cellar/cairo/1.18.2/include/cairo -I/opt/homebrew/Cellar/fontconfig/2.15.0/include -I/opt/homebrew/opt/freetype/include/freetype2 -I/opt/homebrew/Cellar/libxext/1.3.6/include -I/opt/homebrew/Cellar/xorgproto/2024.1/include -I/opt/homebrew/Cellar/libxrender/0.9.11/include -I/opt/homebrew/Cellar/libx11/1.8.10/include -I/opt/homebrew/Cellar/libxcb/1.17.0/include -I/opt/homebrew/Cellar/libxau/1.0.11/include -I/opt/homebrew/Cellar/libxdmcp/1.1.5/include -I/opt/homebrew/Cellar/pixman/0.44.0/include/pixman-1 -I/opt/homebrew/Cellar/gdk-pixbuf/2.42.12/include/gdk-pixbuf-2.0 -I/opt/homebrew/opt/libpng/include/libpng16 -I/opt/homebrew/Cellar/libtiff/4.7.0/include -I/opt/homebrew/opt/zstd/include -I/opt/homebrew/Cellar/xz/5.6.3/include -I/opt/homebrew/Cellar/jpeg-turbo/3.0.4/include -I/opt/homebrew/Cellar/at-spi2-core/2.54.0/include/atk-1.0 -I/opt/homebrew/Cellar/libepoxy/1.5.10/include -I/opt/homebrew/Cellar/fribidi/1.0.16/include/fribidi -I/opt/homebrew/Cellar/glib/2.82.2/include/gio-unix-2.0 -I/opt/homebrew/Cellar/glib/2.82.2/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk/usr/include/ffi -I/opt/homebrew/Cellar/glib/2.82.2/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.82.2/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/Cellar/pcre2/10.44/include -I/opt/homebrew/Cellar/gtksourceview4/4.8.4_1/include/gtksourceview-4 -I/opt/homebrew/Cellar/gtk+3/3.24.43/include/gtk-3.0 -I/opt/homebrew/Cellar/pango/1.54.0/include/pango-1.0 -I/opt/homebrew/Cellar/harfbuzz/10.1.0/include/harfbuzz -I/opt/homebrew/Cellar/graphite2/1.3.14/include -I/opt/homebrew/Cellar/cairo/1.18.2/include -I/opt/homebrew/Cellar/cairo/1.18.2/include/cairo -I/opt/homebrew/Cellar/fontconfig/2.15.0/include -I/opt/homebrew/opt/freetype/include/freetype2 -I/opt/homebrew/Cellar/libxext/1.3.6/include -I/opt/homebrew/Cellar/xorgproto/2024.1/include -I/opt/homebrew/Cellar/libxrender/0.9.11/include -I/opt/homebrew/Cellar/libx11/1.8.10/include -I/opt/homebrew/Cellar/libxcb/1.17.0/include -I/opt/homebrew/Cellar/libxau/1.0.11/include -I/opt/homebrew/Cellar/libxdmcp/1.1.5/include -I/opt/homebrew/Cellar/pixman/0.44.0/include/pixman-1 -I/opt/homebrew/Cellar/gdk-pixbuf/2.42.12/include/gdk-pixbuf-2.0 -I/opt/homebrew/opt/libpng/include/libpng16 -I/opt/homebrew/Cellar/libtiff/4.7.0/include -I/opt/homebrew/opt/zstd/include -I/opt/homebrew/Cellar/xz/5.6.3/include -I/opt/homebrew/Cellar/jpeg-turbo/3.0.4/include -I/opt/homebrew/Cellar/at-spi2-core/2.54.0/include/atk-1.0 -I/opt/homebrew/Cellar/libepoxy/1.5.10/include -I/opt/homebrew/Cellar/glib/2.82.2/include/gio-unix-2.0 -I/opt/homebrew/Cellar/glib/2.82.2/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk/usr/include/ffi -I/opt/homebrew/Cellar/glib/2.82.2/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.82.2/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/Cellar/pcre2/10.44/include -I/opt/homebrew/Cellar/fribidi/1.0.16/include/fribidi -I/opt/homebrew/Cellar/spread-sheet-widget/0.10/include -I/opt/homebrew/Cellar/gtk+3/3.24.43/include/gtk-3.0 -I/opt/homebrew/Cellar/pango/1.54.0/include/pango-1.0 -I/opt/homebrew/Cellar/harfbuzz/10.1.0/include/harfbuzz -I/opt/homebrew/Cellar/graphite2/1.3.14/include -I/opt/homebrew/Cellar/cairo/1.18.2/include -I/opt/homebrew/Cellar/cairo/1.18.2/include/cairo -I/opt/homebrew/Cellar/fontconfig/2.15.0/include -I/opt/homebrew/opt/freetype/include/freetype2 -I/opt/homebrew/Cellar/libxext/1.3.6/include -I/opt/homebrew/Cellar/xorgproto/2024.1/include -I/opt/homebrew/Cellar/libxrender/0.9.11/include -I/opt/homebrew/Cellar/libx11/1.8.10/include -I/opt/homebrew/Cellar/libxcb/1.17.0/include -I/opt/homebrew/Cellar/libxau/1.0.11/include -I/opt/homebrew/Cellar/libxdmcp/1.1.5/include -I/opt/homebrew/Cellar/pixman/0.44.0/include/pixman-1 -I/opt/homebrew/Cellar/gdk-pixbuf/2.42.12/include/gdk-pixbuf-2.0 -I/opt/homebrew/opt/libpng/include/libpng16 -I/opt/homebrew/Cellar/libtiff/4.7.0/include -I/opt/homebrew/opt/zstd/include -I/opt/homebrew/Cellar/xz/5.6.3/include -I/opt/homebrew/Cellar/jpeg-turbo/3.0.4/include -I/opt/homebrew/Cellar/at-spi2-core/2.54.0/include/atk-1.0 -I/opt/homebrew/Cellar/libepoxy/1.5.10/include -I/opt/homebrew/Cellar/fribidi/1.0.16/include/fribidi -I/opt/homebrew/Cellar/glib/2.82.2/include/gio-unix-2.0 -I/opt/homebrew/Cellar/glib/2.82.2/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk/usr/include/ffi -I/opt/homebrew/Cellar/glib/2.82.2/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.82.2/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/Cellar/pcre2/10.44/include -Wall -Wextra -Wwrite-strings -Wstrict-prototypes -Wpointer-arith -Wno-sign-compare -Wmissing-prototypes -DGDK_MULTIHEAD_SAFE=1 -Wno-unused-parameter -g -O2 -DGCC_LINT -o src/ui/gui/.libs/psppire src/ui/gui/psppire-builder-wrapper.o src/ui/gui/psppire-entry-dialog.o src/ui/gui/psppire-executor.o src/ui/gui/psppire-find-dialog.o src/ui/gui/psppire-goto-case-dialog.o src/ui/gui/psppire-helper.o src/ui/gui/psppire-help-menu.o src/ui/gui/psppire-main.o src/ui/gui/psppire-missing-val-dialog.o src/ui/gui/psppire-options-dialog.o src/ui/gui/psppire-psppire.o src/ui/gui/psppire-psppire-data-editor.o src/ui/gui/psppire-psppire-data-store.o src/ui/gui/psppire-psppire-data-window.o src/ui/gui/psppire-psppire-delimited-text.o src/ui/gui/psppire-psppire-encoding-selector.o src/ui/gui/psppire-psppire-import-assistant.o src/ui/gui/psppire-psppire-import-spreadsheet.o src/ui/gui/psppire-psppire-import-textfile.o src/ui/gui/psppire-psppire-lex-reader.o src/ui/gui/psppire-psppire-output-view.o src/ui/gui/psppire-psppire-output-window.o src/ui/gui/psppire-psppire-scanf.o src/ui/gui/psppire-psppire-spreadsheet-data-model.o src/ui/gui/psppire-psppire-spreadsheet-model.o src/ui/gui/psppire-psppire-syntax-window.o src/ui/gui/psppire-psppire-value-entry.o src/ui/gui/psppire-psppire-window.o src/ui/gui/psppire-psppire-window-register.o src/ui/gui/psppire-t-test-options.o src/ui/gui/psppire-val-labs-dialog.o src/ui/gui/psppire-value-variant.o src/ui/gui/psppire-var-display.o src/ui/gui/psppire-var-type-dialog.o src/ui/gui/psppire-widget-io.o src/ui/gui/psppire-windows-menu.o src/ui/gui/psppire-psppire-marshal.o src/ui/gui/psppire-resources.o -Wl,-framework -Wl,Cocoa -Wl,-framework -Wl,Carbon -Wl,-framework -Wl,CoreGraphics -Wl,-framework -Wl,Cocoa -Wl,-framework -Wl,Carbon -Wl,-framework -Wl,CoreGraphics -Wl,-framework -Wl,Cocoa -Wl,-framework -Wl,Carbon -Wl,-framework -Wl,CoreGraphics -Wl,-framework -Wl,CoreFoundation -Wl,-framework -Wl,CoreServices -Wl,-framework -Wl,CoreFoundation -Wl,-framework -Wl,CoreServices  src/ui/gui/.libs/libwidgets-essential.a src/ui/.libs/libuicommon.a src/.libs/libpspp.dylib -L/opt/homebrew/Cellar/pango/1.54.0/lib -L/opt/homebrew/Cellar/glib/2.82.2/lib -L/opt/homebrew/opt/gettext/lib -L/opt/homebrew/Cellar/harfbuzz/10.1.0/lib -L/opt/homebrew/Cellar/cairo/1.18.2/lib -L/usr/lib -L/opt/homebrew/Cellar/gsl/2.8/lib src/.libs/libpspp-core.dylib -lxml2 -L/opt/homebrew/Cellar/gtk+3/3.24.43/lib -L/opt/homebrew/Cellar/at-spi2-core/2.54.0/lib -L/opt/homebrew/Cellar/gdk-pixbuf/2.42.12/lib -lgthread-2.0 -L/opt/homebrew/Cellar/gtksourceview4/4.8.4_1/lib -lgtksourceview-4 -L/opt/homebrew/Cellar/spread-sheet-widget/0.10/lib -lspread-sheet-widget -lgtk-3 -lgdk-3 -latk-1.0 -lcairo-gobject -lgdk_pixbuf-2.0 -lgio-2.0 -lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lcairo -lgsl -lm -liconv -lreadline -lgslcblas -lz -lintl
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/fredowski/homebrew-pspp/issues
```

**Comment by davert318** [comment]
Same here. 

Last 15 lines from /Users/dave/Library/Logs/Homebrew/pspp/02.make:
libtool: link: clang -Wall -Wextra -Wwrite-strings -Wstrict-prototypes -Wpointer-arith -Wno-sign-compare -Wmissing-prototypes -g -O2 -DGCC_LINT -o utilities/.libs/pspp-output utilities/pspp_output-pspp-output.o -Wl,-framework -Wl,CoreFoundation -Wl,-framework -Wl,CoreServices  -L/usr/lib src/.libs/libpspp.dylib -L/usr/local/Cellar/pango/1.54.0/lib -L/usr/local/Cellar/glib/2.82.2/lib -L/usr/local/opt/gettext/lib -L/usr/local/Cellar/harfbuzz/10.1.0/lib -L/usr/local/Cellar/cairo/1.18.2/lib -L/usr/local/Cellar/gsl/2.8/lib -lgsl -lm src/.libs/libpspp-core.dylib -lxml2 -lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lcairo -liconv -lreadline -lgslcblas -lz -lintl
libtool: link: clang -Wall -Wextra -Wwrite-strings -Wstrict-prototypes -Wpointer-arith -Wno-sign-compare -Wmissing-prototypes -g -O2 -DGCC_LINT -o utilities/.libs/pspp-convert utilities/pspp_convert-pspp-convert.o -Wl,-framework -Wl,CoreFoundation -Wl,-framework -Wl,CoreServices  src/.libs/libpspp.dylib -L/usr/local/Cellar/pango/1.54.0/lib -L/usr/local/Cellar/glib/2.82.2/lib -L/usr/local/opt/gettext/lib -L/usr/local/Cellar/harfbuzz/10.1.0/lib -L/usr/local/Cellar/cairo/1.18.2/lib -L/usr/lib -L/usr/local/Cellar/gsl/2.8/lib -lgsl -lm src/.libs/libpspp-core.dylib -lxml2 -lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lcairo -liconv -lreadline -lgslcblas -lz -lintl
libtool: link: clang -Wall -Wextra -Wwrite-strings -Wstrict-prototypes -Wpointer-arith -Wno-sign-compare -Wmissing-prototypes -g -O2 -DGCC_LINT -o src/ui/terminal/.libs/pspp -Wl,-framework -Wl,CoreFoundation -Wl,-framework -Wl,CoreServices  src/ui/terminal/.libs/libui.a src/ui/.libs/libuicommon.a src/.libs/libpspp.dylib -L/usr/local/Cellar/pango/1.54.0/lib -L/usr/local/Cellar/glib/2.82.2/lib -L/usr/local/opt/gettext/lib -L/usr/local/Cellar/harfbuzz/10.1.0/lib -L/usr/local/Cellar/cairo/1.18.2/lib -L/usr/lib -L/usr/local/Cellar/gsl/2.8/lib src/.libs/libpspp-core.dylib -lxml2 -lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lcairo -lgsl -lm -liconv -lreadline -lgslcblas -lz -lintl
Undefined symbols for architecture x86_64:
  "_rl_catch_signals", referenced from:
      _terminal_reader_create in libui.a[4](libui_la-terminal-reader.o)
  "_rl_echo_signal_char", referenced from:
      _handler in libui.a[4](libui_la-terminal-reader.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by davert318** [comment]
Brew Doctor says: 
Warning: Your Homebrew's prefix is not /opt/homebrew.
Is that the core problem? Building PSPP did work before. 
Mac Mini M2

**Comment by davert318** [comment]
I uninstalled brew entirely - which is an ordeal in itself, really, taking several tries and manual interventions - and started over. It's been stalling in make, so it'll be a while before I have a final answer, but I think the issue is I moved from an Intel to an M2 and this is the first time I've tried PSPP updates.

**Comment by davert318** [comment]
no dice.

brew doctor seems happy - 
% brew doctor
Your system is ready to brew.



==> Formula
Tap: fredowski/pspp
Path: /opt/homebrew/Library/Taps/fredowski/homebrew-pspp/Formula/pspp.rb
==> Configuration
HOMEBREW_VERSION: 4.4.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 254bf3fe9d8fa2e1b2fb55dbcf535b2d870180c4
Last commit: 3 days ago
Core tap JSON: 14 Nov 18:10 UTC
Core cask tap JSON: 14 Nov 18:10 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: 10-core 64-bit arm_blizzard_avalanche
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: N/A
Rosetta 2: false
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j10
CMAKE_PREFIX_PATH: /opt/homebrew/opt/readline:/opt/homebrew/opt/sqlite:/opt/homebrew/opt/icu4c@76:/opt/homebrew
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /opt/homebrew/opt/python@3.13/Frameworks

**Comment by fredowski** [comment]
So now this happens on my MacOS 12.7.6 Intel Macbook Pro also. I figured out that this is related to the readline library which is accessed for example here: https://git.savannah.gnu.org/cgit/pspp.git/tree/src/ui/terminal/terminal-reader.c#n313

Up to now pspp links to the native MacOS readline library. It seems that Apple has removed some parts of the functionality. So I will link to the homebrew readline library instead.

Thanks for reporting and checking the bug!
